// 03-Аквариум/trout/src/app/page.tsx
'use client';

import { useState } from 'react';

export default function Home() {
  const [message, setMessage] = useState('Привет, Форель!');

  const handleClick = () => {
    setMessage('Ты кликнула на рыбу!');
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-blue-100">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-blue-800 mb-4">🐟 Форель в Аквариуме</h1>
        <p className="text-xl text-blue-600 mb-6">{message}</p>
        <button
          onClick={handleClick}
          className="px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-700 transition"
        >
          Кликни на рыбу
        </button>
      </div>
    </div>
  );
}

// 03-Аквариум/mackerel/app/app.vue
<template>
  <div class="min-h-screen bg-green-100 flex items-center justify-center">
    <div class="text-center">
      <h1 class="text-4xl font-bold text-green-800 mb-4">
        🐟 Скумбрия в Аквариуме
      </h1>
      <p class="text-xl text-green-600 mb-6">{{ message }}</p>
      <button
        @click="changeMessage"
        class="px-6 py-3 bg-green-500 text-white rounded-lg hover:bg-green-700 transition"
      >
        Кликни на рыбу
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
const message = ref("Привет, Скумбрия!");

const changeMessage = () => {
  message.value = "Ты кликнула на рыбу!";
};
</script>
